
Java Exception propagation
An exception is first thrown   and if it is not caught using try catch block ,
     we declare the exception in method definition.
     it drops down the call stack to the calling previous method,
     A method calling another method, that calling one more method 
            is known as Stack or Stack Trace
     
 
 If not caught there, the exception again drops down 
   to the calling next level previous method, 
   and so on until they are caught or until they reach the very bottom of the call stack.
   
 
 This is called exception propagation.
 


class TestExceptionPropagation1{  
  void m(){  
    int data=50/0;  
  }  
  void n(){  
    m();  
  }  
  void p(){  
   try{  
    n();  
   }catch(Exception e){System.out.println("exception handled");}  
  }  
  public static void main(String args[]){  
   TestExceptionPropagation1 obj=new TestExceptionPropagation1();  
   obj.p();  
   System.out.println("normal flow...");  
  }  
}  